import '/imports/api/courses/methods.js';
import '/imports/api/courses/server/publications.js';
import '/imports/api/course-discussions/methods.js';
import '/imports/api/course-discussions/server/publications.js';
import '/imports/api/groups/methods.js';
import '/imports/api/groups/server/publications.js';
import '/imports/api/regions/methods.js';
import '/imports/api/regions/server/publications.js';
import '/imports/api/version/server/publications.js';
